import { createClient } from '@/lib/supabase/server';

type AdminUser = { id: string; email: string | null; display_name: string | null; role: string; is_onboarded: boolean; last_login_at: string | null; created_at: string };
type RpcClient = { rpc(name: string): Promise<{ data: { recent_users: AdminUser[]; users_total: number; users_admin: number; users_owner: number; users_onboarded: number; users_active_7d: number } | null; error: { message: string } | null }> };

export default async function AdminUsersPage() {
  const supabase = await createClient();
  const { data, error } = await (supabase as unknown as RpcClient).rpc('admin_platform_snapshot');
  if (error || !data) throw new Error(error?.message || 'Admin user data unavailable');
  const stats = [['All users', data.users_total], ['Admins', data.users_admin], ['Owners', data.users_owner], ['Onboarded', data.users_onboarded], ['Active 7d', data.users_active_7d]];
  return <div className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-amber-600">Platform / Accounts</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Users & accounts</h1><p className="mt-2 text-sm text-slate-500">The complete account population from Supabase, including privileged roles and recent activity.</p></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{stats.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-medium text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold">{value}</div></div>)}</div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50"><tr><th className="px-5 py-3">Account</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Onboarding</th><th className="px-5 py-3">Last login</th><th className="px-5 py-3">Created</th><th className="px-5 py-3">Protection</th></tr></thead><tbody className="divide-y divide-slate-100">{data.recent_users.map((user) => <tr key={user.id} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="font-semibold">{user.display_name || user.email?.split('@')[0] || 'Unnamed user'}</div><div className="text-xs text-slate-400">{user.email || user.id}</div></td><td className="px-5 py-4"><span className={user.role === 'owner' ? 'rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold uppercase text-amber-800' : user.role === 'admin' ? 'rounded-full bg-blue-100 px-2.5 py-1 text-xs font-bold uppercase text-blue-800' : 'rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold uppercase text-slate-600'}>{user.role}</span></td><td className="px-5 py-4">{user.is_onboarded ? 'Complete' : 'Pending'}</td><td className="px-5 py-4 text-slate-500 font-mono text-xs">{user.last_login_at ? new Date(user.last_login_at).toLocaleString('en-US') : 'Never'}</td><td className="px-5 py-4 text-slate-500 font-mono text-xs">{new Date(user.created_at).toLocaleDateString('en-US')}</td><td className="px-5 py-4">{user.role === 'owner' ? <span className="text-xs font-bold text-amber-700">IMMUTABLE OWNER</span> : user.role === 'admin' ? <span className="text-xs font-semibold text-slate-600">DELETE BLOCKED</span> : <span className="text-xs text-slate-400">Standard</span>}</td></tr>)}</tbody></table></div></div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Privileged account protection</h2><p className="mt-2 text-sm leading-6 text-amber-900/80">The database now blocks deletion of every admin/owner row and blocks demotion of the owner. This is enforced below the UI, so a compromised client cannot bypass it through a normal Supabase request.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Account changes</h2><p className="mt-2 text-sm leading-6 text-slate-500">Role changes and destructive account operations should go through a verified server-side workflow. Do not expose raw role updates to the browser.</p></div></div>
  </div>;
}
