'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowUpRight, Bot, CheckCircle2, ChevronRight, CircleAlert, FileText, Loader2, Play, Target, Users } from 'lucide-react';
import { toast } from 'sonner';
import { getDashboardOverviewData, type DashboardOverviewData } from './actions';
import { startVisibilityScanAction } from '@/app/(dashboard)/projects/scan-actions';
import { Button } from '@/components/ui/button';

interface Props { projectId: string; initialData?: DashboardOverviewData; }

function Metric({ label, value, change, icon: Icon }: { label: string; value: string; change?: string; icon: typeof Target }) {
  return <div className="border-b border-slate-200 pb-5 sm:border-b-0 sm:border-r sm:pr-6 last:border-0"><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><Icon className="h-4 w-4" />{label}</div><div className="mt-2 flex items-end gap-2"><span className="text-3xl font-semibold tracking-[-.04em] text-slate-950">{value}</span>{change && <span className="mb-1 text-xs font-semibold text-emerald-600">{change}</span>}</div></div>;
}

function Trend({ points }: { points: number[] }) {
  const safe = points.length > 1 ? points : [18, 22, 20, 28, 34, 31, 40];
  const max = Math.max(...safe, 1); const min = Math.min(...safe); const range = Math.max(max - min, 1);
  const d = safe.map((v, i) => `${i ? 'L' : 'M'} ${(i / (safe.length - 1)) * 100} ${95 - ((v - min) / range) * 80}`).join(' ');
  return <div className="relative h-56"><div className="absolute inset-0 flex flex-col justify-between border-b border-slate-100 text-[10px] text-slate-400"><span>High</span><span>Medium</span><span>Low</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-x-8 top-2 h-[calc(100%-22px)] w-[calc(100%-32px)]"><path d={d} fill="none" stroke="currentColor" strokeWidth="1.8" vectorEffect="non-scaling-stroke" className="text-slate-950" /></svg><div className="absolute bottom-0 left-8 right-0 flex justify-between text-[10px] text-slate-400"><span>30d ago</span><span>15d</span><span>Today</span></div></div>;
}

export function DashboardPremiumClientView({ projectId, initialData }: Props) {
  const [triggering, setTriggering] = useState(false); const [running, setRunning] = useState(false);
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ['dashboardOverview', projectId], queryFn: async () => { const r = await getDashboardOverviewData(projectId); if (!r.success || !r.data) throw new Error(r.error || 'Unable to load dashboard'); return r.data; }, initialData, staleTime: 30000 });
  useEffect(() => { if (!running) return; const id = window.setInterval(async () => { const r = await refetch(); const s = r.data?.latestScan?.status?.toLowerCase(); if (s === 'completed' || s === 'failed' || s === 'cancelled') setRunning(false); }, 2500); return () => window.clearInterval(id); }, [running, refetch]);
  const start = async () => { setTriggering(true); setRunning(true); try { const r = await startVisibilityScanAction(projectId); if (!r.success) { setRunning(false); toast.error(r.error || 'Unable to start scan'); } else { toast.success('Scan started'); await refetch(); } } catch { setRunning(false); toast.error('Unable to start scan'); } finally { setTriggering(false); } };

  if (isLoading && !data) return <div className="space-y-6"><div className="h-40 animate-pulse rounded-2xl bg-slate-100" /><div className="h-72 animate-pulse rounded-2xl bg-slate-100" /><div className="grid gap-4 md:grid-cols-3"><div className="h-32 animate-pulse rounded-2xl bg-slate-100" /><div className="h-32 animate-pulse rounded-2xl bg-slate-100" /><div className="h-32 animate-pulse rounded-2xl bg-slate-100" /></div></div>;
  if (isError || !data) return <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center"><CircleAlert className="mx-auto h-6 w-6 text-red-600" /><h2 className="mt-3 font-semibold text-slate-950">We couldn't load your workspace</h2><Button variant="outline" className="mt-4" onClick={() => refetch()}>Try again</Button></div>;

  const score = data.latestScan?.visibilityScore ?? data.visibility.currentScore ?? 0;
  const points = data.visibility.mentionHistory.map((x) => x.score);
  const latest = points.length ? points[points.length - 1] : 0;
  const previous = points.length > 1 ? points[points.length - 2] : latest;
  const delta = previous ? `${(((latest - previous) / previous) * 100).toFixed(1)}%` : undefined;
  const recommendations = [...data.recommendations.criticalList, ...data.recommendations.highPriorityList];
  const activities = data.recentActivity.recentJobs;
  const citations = data.competitors.citationComparison.reduce((sum, item) => sum + item.citationCount, 0);

  return <div className="space-y-8 pb-10">
    <section className="flex flex-col gap-5 border-b border-slate-200 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Workspace overview</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950 sm:text-4xl">{data.project.name}</h1><p className="mt-2 text-sm text-slate-500">A clear view of how AI systems discover and describe your brand.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/scans" className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-slate-300">Scan history <ArrowUpRight className="h-4 w-4" /></Link><Button onClick={start} disabled={triggering || running} className="gap-2 bg-slate-950 text-white hover:bg-slate-800">{triggering ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />} {running ? 'Scan running' : 'Start scan'}</Button></div></section>

    {running && <div className="flex items-center gap-3 border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700"><Loader2 className="h-4 w-4 animate-spin text-slate-950" /> Your scan is running. This view will refresh automatically.</div>}

    <section className="grid gap-6 lg:grid-cols-[1.45fr_.55fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-start justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">AI visibility score</div><div className="mt-2 flex items-baseline gap-3"><span className="text-6xl font-semibold tracking-[-.06em] text-slate-950">{score}</span><span className="text-sm text-slate-400">/ 100</span></div></div><span className="inline-flex h-fit items-center gap-1.5 rounded-full bg-slate-50 px-3 py-1.5 text-xs font-semibold text-slate-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" /> {data.latestScan ? data.latestScan.status : 'Awaiting scan'}</span></div><div className="mt-8"><Trend points={points} /></div></div><div className="rounded-2xl bg-slate-950 p-6 text-white sm:p-7"><div className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Latest signal</div><div className="mt-5 text-4xl font-semibold tracking-[-.05em]">{latest || '—'}<span className="ml-2 text-sm font-normal text-slate-400">visibility</span></div><div className="mt-2 text-sm font-semibold text-emerald-400">{delta ? `${delta} vs previous` : 'Run another scan to establish a trend'}</div><p className="mt-8 text-sm leading-6 text-slate-400">Open a report to see the evidence behind the score and understand what to improve next.</p><Link href="/dashboard/scans" className="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-white hover:underline">Open reports <ChevronRight className="h-4 w-4" /></Link></div></section>

    <section className="grid gap-6 border-y border-slate-200 py-7 sm:grid-cols-2 lg:grid-cols-4"><Metric label="AI visibility" value={`${score}`} icon={Bot} /><Metric label="Citations" value={String(citations)} icon={FileText} /><Metric label="Open recommendations" value={String(recommendations.length)} icon={Target} /><Metric label="Competitors tracked" value={String(data.competitors.topCompetitors.length)} icon={Users} /></section>

    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><div><h2 className="font-semibold text-slate-950">Priority actions</h2><p className="mt-1 text-xs text-slate-500">The clearest opportunities from your latest analysis.</p></div><Link href="/dashboard/recommendations" className="text-xs font-semibold text-slate-600 hover:text-slate-950">View all</Link></div><div className="divide-y divide-slate-100">{recommendations.slice(0, 4).map((r, i) => <Link key={r.id} href="/dashboard/recommendations" className="flex items-center gap-4 px-6 py-4 hover:bg-slate-50"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-slate-200 text-xs font-semibold">{i + 1}</span><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium text-slate-900">{r.title}</div><div className="mt-1 text-xs text-slate-500">{r.category}</div></div><ChevronRight className="h-4 w-4 text-slate-400" /></Link>)}{recommendations.length === 0 && <div className="px-6 py-10 text-center text-sm text-slate-500">No recommendations yet. A completed scan will surface opportunities here.</div>}</div></div><div className="rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-6 py-5"><h2 className="font-semibold text-slate-950">Recent activity</h2><p className="mt-1 text-xs text-slate-500">The latest workspace jobs.</p></div><div className="divide-y divide-slate-100">{activities.slice(0, 5).map((a) => <div key={a.id} className="flex gap-3 px-6 py-4"><div className="mt-1 h-2 w-2 shrink-0 rounded-full bg-slate-300" /><div><div className="text-sm text-slate-700">{a.jobType}</div><div className="mt-1 text-xs text-slate-400">{a.status} · {new Date(a.createdAt).toLocaleDateString()}</div></div></div>)}{activities.length === 0 && <div className="px-6 py-10 text-center text-sm text-slate-500">Activity will appear here as your workspace changes.</div>}</div></div></section>

    <section className="rounded-2xl border border-slate-200 bg-slate-50 p-6 sm:p-7"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-slate-950"><CheckCircle2 className="h-4 w-4 text-emerald-600" /> Evidence-first visibility intelligence</div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">The workspace is organized around measurable signals and evidence rather than decorative metrics. Drill into a report to understand what changed and what to do next.</p></div><Link href="/dashboard/scans" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm ring-1 ring-slate-200 hover:ring-slate-300">Browse reports <ArrowUpRight className="h-4 w-4" /></Link></div></section>
  </div>;
}
