'use client';

import React, { useState } from 'react';
import { ChevronDown } from 'lucide-react';

const faqs = [
  {
    question: 'What is AI Search Engine Visibility?',
    answer:
      'AI Search Engine Visibility measures how frequently and accurately your brand, products, and domain URLs are cited or recommended by conversational AI engines like Gemini, ChatGPT, Claude, and Perplexity when users query relevant topics.',
  },
  {
    question: 'How does AI Visibility OS audit my domain?',
    answer:
      'AI Visibility OS runs prompt benchmark scans against AI models, parses the response text for brand mentions and external citations, and calculates a normalized visibility score alongside actionable optimization tasks.',
  },
  {
    question: 'How is this different from traditional SEO keyword tools?',
    answer:
      'Traditional SEO tracks rank positions on search engine results pages (SERPs). AI Visibility OS measures synthetic answers generated by generative AI models, where traditional rank positions do not exist.',
  },
  {
    question: 'Which AI platforms are currently supported?',
    answer:
      'Google Gemini is currently active in audit scans. Groq, OpenAI GPT-4o, and Anthropic Claude integration support are coming soon.',
  },
  {
    question: 'Is my data secure?',
    answer:
      'Yes. AI Visibility OS is built with strict tenant isolation, role-based access control, and enterprise-grade data protection standards.',
  },
];

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section className="py-20 bg-slate-50/50 border-b border-slate-200/60">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="text-center space-y-4 mb-16">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">
            Frequently Asked Questions
          </h2>
          <p className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
            Everything you need to know
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={index}
                className="rounded-xl border border-slate-200 bg-white shadow-2xs overflow-hidden transition-colors"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : index)}
                  className="flex w-full items-center justify-between p-5 text-left text-sm font-semibold text-slate-900 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950"
                  aria-expanded={isOpen}
                >
                  <span>{faq.question}</span>
                  <ChevronDown
                    className={`h-4 w-4 text-slate-500 transition-transform duration-200 ${
                      isOpen ? 'rotate-180' : ''
                    }`}
                  />
                </button>
                {isOpen && (
                  <div className="px-5 pb-5 text-sm text-slate-600 border-t border-slate-100 pt-3 leading-relaxed">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
